version: "1.0"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - c8413:/caller8413backend
    depends_on:
      - db
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - c8413
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - c8413
volumes:
  c8413:
networks:
  c8413:
    external: true
    driver: bridge
